config/routes.rb
Rails.application.routes.draw do
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# frozen_string_literal: true
# Generated with `rails generate valkyrie:model Item`
class Item < Valkyrie::Resource
  include Valkyrie::Resource::AccessControls
  attribute :label, Valkyrie::Types::String
end

app/models/item_change_set.rb
class ItemChangeSet < Valkyrie::ChangeSet
  self.fields = [:label]
  validates :label, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :update, :destroy]
  before_action :find_item_change_set, only: [:edit]

  delegate :persister, :query_service, to: :metadata_adapter

  # GET /items
  def index
    # TODO: Get items beyond first page
    @items = query_service.find_all_of_model(model: Item).map do |hash|
      puts "reifying an item with #{hash.symbolize_keys}"
      Item.new(hash.symbolize_keys)
    end
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = ItemChangeSet.new(Item.new)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = change_set_for(resource: Item.new(item_params))

    if change_set_persister.save(change_set: @item)
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = change_set_for(resource: @item)

    if change_set_persister.save(change_set: @item)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    persister.delete(resource: @item)
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  def change_set_for(resource:)
    change_set = ItemChangeSet.new(resource)
    change_set.validate(item_params)
    change_set.sync
    change_set
  end

  # Use callbacks to share common setup or constraints between actions.
  def find_item
    @item = Item.new(query_service.find_by(id: params[:id]).symbolize_keys)
  end

  def find_item_change_set
    @item = ItemChangeSet.new(find_item)
  end

  # Only allow a trusted parameter "white list" through.
  def item_params
    params.require(:item).permit(:label)
  end

  def metadata_adapter
    Valkyrie.config.metadata_adapter
  end

  def change_set_persister
    ChangeSetPersister.new(metadata_adapter: metadata_adapter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.label %></td>
        <td><%= link_to 'Show', item_path(item.to_param) %></td>
        <td><%= link_to 'Edit', edit_item_path(item.to_param) %></td>
        <td><%= link_to 'Destroy', item_path(item.to_param), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @item.label %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sigrdrifa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>